### ISSUE TITLE
Softlock in Booster's Tower

### ISSUE THREAD

**Issue by MetroidMst** [abyssonym/smrpg_gbarp#8]
I came across this bug while talking to the first Snifit in Booster's Tower. After defeating it, I got a dialog box that was wrong, and the game softlocked after defeating another enemy that jumped into the fight. I have included a link to my stream and the timestamp the fight begins at.

Seed: 1474920601
Emulator: SNES9x 1.53

http://www.hitbox.tv/video/1157819 - Begins at 59:47

I avoided the other Snifit's later on in the tower, so I have no idea if they have any issues currently.

**Comment by abyssonym** [comment]
I believe this is because there is a battle event associated with the snifit, and there's not supposed to be so many enemies in that battle. I've added the snifit to the boss pool to prevent its formations from getting randomized, and hopefully that will fix the issue (feel free to reopen this issue if it persists).
